### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by shunopoli** [wtcross/aws-overseer#2]
Thanks for writing this but having an issue. Not sure I understand the configuration setup. I see in your example playbook you have hosts: overseer.  Do you have this is a group in your inventory? I am confused on how it knows what host to run on. 

Is this the scheduling  cron run on a control node that's always on? If you could guide in a basic config example for starting/stoping instance it would be appreciated.

**Comment by wtcross** [comment]
I completely understand how this is confusing. The word "overseer" is used too much! That's probably a result of this project being a proof of concept. It's definitely rough around the edges. Thanks in advance for checking it out.

The example playbook I show in [the readme](https://github.com/wtcross/aws-overseer/blob/master/README.md) is targeting a single host group (with one host) called `overseer`. The idea in the example is that there is one host (`overseer`) controlling one or more logical aws-overseers. This is where the `aws-overseer` role comes into play.

The role configures logical overseers on the target host. These are each specific to an AWS region, can be configured for enforcement (strict requirement of tags), and each have their own "start-stop-schedules", which are each a set of cron jobs that run on the control host (`overseer`) to start and stop instances on a configurable schedule. AWS EC2 tags are the identifier used to determine if an instance is in a specific schedule.

The general steps are:
1. create an overseer control host or use an existing host
2. configure the control host using the `aws-overseer` role
    - define your start-stop-schedules
3. when creating instances apply appropriate tags (Overseer, StartStopSchedule) to have them managed by the correct overseer
    - it's possible to turn on enforcement for a specific overseer, which will stop instances that don't have the correct tags

Does that help? Keep in mind this was a fun experiment and I wanted to try and use Ansible in this way. It was useful in practice, but there are probably other ways to accomplish this in AWS since. An alternative to crons would be to make this role simply configure [scheduled AWS Lambda functions](http://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html) that hit the AWS API to do the same thing the crons are doing. It should be much simpler in practice and also removes the pain of making sure the control host stays up.

Thanks!
-Tyler

**Comment by shunopoli** [comment]
Hey thanks for the feedback and explanation. I actually did go with lambda and python script. I didn't want to have a host be responsible for managing my nodes as it was something else to manage.

**Comment by wtcross** [comment]
I think that's the right way to go. This was created before you could schedule running lambdas, otherwise I would have just done that.
